spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

server:
  port: 8084

springdoc:
  packages-to-scan: com.example.task_management_system_rest.endpoint
  site:
    url: http://localhost:8080